modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/jo-devnull/minepkl/issues"
license = "MIT"

[[mods]]
modId = "minepkl"
version = "${version}"
displayName = "Minepkl"
authors = "jo-devnull"
description = '''
Tool for modpack developers to generate minecraft resources using the Pkl language.
'''
#logoFile = ""

[[dependencies.minepkl]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minepkl]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "minepkl.mixins.json"
